<?php



namespace App\test;

require "model/visitor.php";

use App\model\visitor;
use PHPUnit\Framework\TestCase;

class visitorTest extends TestCase
{
    protected $visitor;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->visitor = new visitor();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->visitor = NULL;
    }

    public function testInscription ()
    {
        $test = $this->visitor->set_inscription("cyriak","leclercq","homme", "cyriakleclercq@gmail.com",27,"fourmies", "modjo", "rien", "test");
        $this->assertEquals('cyriak',$test['name']);
        $this->assertEquals('leclercq',$test['surname']);

    }
}